name: audio_plus
description: "audio_plus plays audio in Flutter apps, offering play, pause, resume, and stop and advanced features for enhanced audio control."
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.audio_plus
        pluginClass: AudioPlusPlugin
      ios:
        pluginClass: AudioPlusPlugin